algo = input('Digite algo:')
print('O tipo primitivo de "{}" é:'.format(algo),type(algo))
print('"{}"é composto de letras?'.format(algo),algo.isalpha())
print('"{}" é composto por números?'.format(algo),algo.isnumeric())
print('"{}" é alfanumerico?'.format(algo),algo.isalnum())
print('"{}" é composto por letras maiúsculas?'.format(algo),algo.isupper())
print('"{}" é composto por letras menúsculas?'.format(algo),algo.islower())
print('"{}" é composto somente por "espaços"?'.format(algo),algo.isspace())
print('"{}" é capitalizado?'.format(algo),algo.istitle())