n = int(input('Digite um número:'))
print('A tabuada de {} é:'.format(n))
print('-'*12)
print(' {} x  2 = {} \n {} x  3 = {}'.format(n,n*2,n,n*3))
print(' {} x  4 = {} \n {} x  5 = {}'.format(n,n*4,n,n*5))
print(' {} x  6 = {} \n {} x  7 = {}'.format(n,n*6,n,n*7))
print(' {} x  8 = {} \n {} x  9 = {}'.format(n,n*8,n,n*9))
print(' {} x 10 = {}'.format(n,n*10))
print('-'*12)